import type { AppLanguage, FilterOperator } from '../domain/types'

const filterOperators = (values: Record<FilterOperator, string>) => values

export const labels = {
  en: {
    settings: 'Settings',
    about: 'About',
    aboutDialog: 'About Parquet Viewer',
    aboutVersion: 'Version 0.1.0',
    aboutEyebrow: 'LOCAL DATA WORKSPACE',
    aboutHeadline: 'See your Parquet data with clarity.',
    aboutDescription: 'A fast, local desktop viewer for Parquet files.',
    aboutDetails: 'Explore schemas, inspect records, and run focused queries with confidence—without moving your data beyond your computer.',
    aboutRepository: 'Repository',
    aboutLicense: 'License',
    aboutAuthor: 'Author',
    closeAbout: 'Close about',
    closeSettings: 'Close settings',
    language: 'Language',
    theme: 'Theme',
    followSystem: 'Follow system',
    light: 'Light',
    dark: 'Dark',
    batchSize: 'Batch size',
    previewRowLimit: 'Preview row limit',
    memoryLimitMb: 'Memory limit MB',
    diskWarningMb: 'Disk warning MB',
    concurrentQueries: 'Concurrent queries',
    temporaryDirectory: 'Temporary directory',
    systemTemporaryDirectory: 'System temporary directory',
    chooseTemporaryDirectory: 'Choose temporary directory',
    useSystemTemporaryDirectory: 'Use system temporary directory',
    restoreTabsOnStartup: 'Restore tabs on startup',
    close: 'Close',
    cancel: 'Cancel',
    saveSettings: 'Save settings',
    settingsSaveFailed: 'Settings could not be saved',
    directorySelectFailed: 'Directory could not be selected',
    openParquetFiles: 'Open Parquet files',
    dropFilesHint: 'Drop one or more files anywhere in this window, or choose them from disk.',
    openingFiles: (count: number) => `Opening ${count} file${count === 1 ? '' : 's'}…`,
    openingFilesProgress: 'Opening files',
    refreshingData: 'Refreshing data',
    reloadingFile: 'Reloading file',
    openFiles: 'Open files',
    closeFile: 'Close',
    closeOtherTabs: 'Close others',
    closeTabsToRight: 'Close right',
    closeTab: (name: string) => `Close ${name}`,
    closeTabsDialog: 'Close files',
    closeTabsMessage: (count: number) => `Close ${count} open file${count === 1 ? '' : 's'}?`,
    closeTabsAction: (count: number) => count === 1 ? 'Close file' : 'Close files',
    copyPath: 'Copy path',
    revealInFileManager: 'Reveal in file manager',
    scrollTabsLeft: 'Scroll tabs left',
    scrollTabsRight: 'Scroll tabs right',
    copyOptions: 'Copy options',
    columnOptions: 'Column options',
    copyCell: 'Copy cell',
    copyRow: 'Copy row',
    copySelection: 'Copy selection',
    visibleColumns: 'Visible columns',
    copiedToClipboard: 'Copied to clipboard',
    couldNotCopyToClipboard: 'Could not copy to clipboard',
    refresh: 'Refresh',
    externalFileChangedTitle: 'File changed externally',
    externalFileChangedMessage: (name: string) => `${name} was modified outside Parquet Viewer. Reload it to view the latest data?`,
    reloadFile: 'Reload file',
    keepCurrentVersion: 'Keep current version',
    statistics: 'Statistics',
    fileStatistics: 'File statistics',
    closeStatistics: 'Close statistics',
    bytes: 'bytes',
    fileSize: 'File size',
    rows: 'rows',
    columns: 'columns',
    rowGroups: 'row groups',
    visibleFields: 'Visible fields',
    showColumn: (name: string) => `Show ${name}`,
    filter: 'Filter',
    sql: 'SQL',
    filterQuery: 'Filter query',
    activeFilters: 'Active filters',
    filterColumn: 'Filter column',
    filterOperator: 'Filter operator',
    filterValue: 'Filter value',
    filterBuilder: 'Build a condition',
    filterConditions: 'Conditions',
    filterEmptyState: 'No conditions yet. Add one above.',
    filterActions: 'Filter actions',
    addCondition: 'Add condition',
    removeFilterCondition: (name: string) => `Remove ${name} condition`,
    clearFilters: 'Clear filters',
    runFilters: 'Run filters',
    previewRows: 'Preview rows',
    choose: 'Choose…',
    filterOperators: filterOperators({
      eq: 'equals', notEq: 'does not equal', lt: 'less than', lte: 'less than or equal',
      gt: 'greater than', gte: 'greater than or equal', contains: 'contains',
      startsWith: 'starts with', endsWith: 'ends with', isNull: 'is null', isNotNull: 'is not null',
    }),
    sqlExamples: 'SQL examples',
    sqlExamplePreview: 'Preview 100 rows',
    sqlExampleCount: 'Count all rows',
    sqlExampleNonNull: 'Find populated first column',
    readOnlySqlTitle: 'Read-only SQL',
    readOnlySqlMessage: 'This viewer is read-only. UPDATE, DELETE, INSERT, and other data-changing statements are not supported.',
    closeReadOnlySql: 'Close read-only notice',
    sqlPreviewRows: 'SQL preview rows',
    formatSql: 'Format SQL',
    runSql: 'Run SQL',
    sqlEditor: 'SQL editor',
    resizeSqlEditor: 'Resize SQL editor',
    table: 'Table',
    errorDetails: 'Error details',
    sqlErrorDetails: 'SQL error details',
    copyDetails: 'Copy details',
    copiedDetails: 'Copied details',
    couldNotCopyDetails: 'Could not copy details',
  },
  zh: {
    settings: '设置',
    about: '关于',
    aboutDialog: '关于 Parquet Viewer',
    aboutVersion: '版本 0.1.0',
    aboutEyebrow: '本地数据工作台',
    aboutHeadline: '让 Parquet 数据，一目了然。',
    aboutDescription: '一款快速、本地运行的 Parquet 文件桌面查看器。',
    aboutDetails: '无需上传或迁移数据，即可浏览结构、查看记录并完成定向查询。',
    aboutRepository: '开源地址',
    aboutLicense: '开源协议',
    aboutAuthor: '作者',
    closeAbout: '关闭关于',
    closeSettings: '关闭设置',
    language: '语言',
    theme: '主题',
    followSystem: '跟随系统',
    light: '浅色',
    dark: '深色',
    batchSize: '批处理大小',
    previewRowLimit: '预览行数上限',
    memoryLimitMb: '内存上限 MB',
    diskWarningMb: '磁盘预警 MB',
    concurrentQueries: '并发查询数',
    temporaryDirectory: '临时目录',
    systemTemporaryDirectory: '系统临时目录',
    chooseTemporaryDirectory: '选择临时目录',
    useSystemTemporaryDirectory: '使用系统临时目录',
    restoreTabsOnStartup: '启动时恢复标签页',
    close: '关闭',
    cancel: '取消',
    saveSettings: '保存设置',
    settingsSaveFailed: '无法保存设置',
    directorySelectFailed: '无法选择目录',
    openParquetFiles: '打开 Parquet 文件',
    dropFilesHint: '将一个或多个文件拖入窗口，或从磁盘中选择。',
    openingFiles: (count: number) => `正在打开 ${count} 个文件…`,
    openingFilesProgress: '正在打开文件',
    refreshingData: '正在刷新数据',
    reloadingFile: '正在重新加载文件',
    openFiles: '打开的文件',
    closeFile: '关闭',
    closeOtherTabs: '关闭其他标签页',
    closeTabsToRight: '关闭右侧标签页',
    closeTab: (name: string) => `关闭 ${name}`,
    closeTabsDialog: '关闭文件',
    closeTabsMessage: (count: number) => `确定关闭 ${count} 个打开的文件吗？`,
    closeTabsAction: (count: number) => count === 1 ? '确认关闭' : '确认关闭',
    copyPath: '复制路径',
    revealInFileManager: '在文件管理器中显示',
    scrollTabsLeft: '向左滚动标签页',
    scrollTabsRight: '向右滚动标签页',
    copyOptions: '复制选项',
    columnOptions: '列设置',
    copyCell: '复制单元格',
    copyRow: '复制行',
    copySelection: '复制所选内容',
    visibleColumns: '显示列',
    copiedToClipboard: '已复制到剪贴板',
    couldNotCopyToClipboard: '无法复制到剪贴板',
    refresh: '刷新',
    externalFileChangedTitle: '文件已在外部修改',
    externalFileChangedMessage: (name: string) => `${name} 已在 Parquet Viewer 外部被修改。是否重新加载以查看最新数据？`,
    reloadFile: '重新加载文件',
    keepCurrentVersion: '保留当前版本',
    statistics: '统计',
    fileStatistics: '文件统计',
    closeStatistics: '关闭统计',
    bytes: '字节',
    fileSize: '文件大小',
    rows: '行',
    columns: '列',
    rowGroups: '行组',
    visibleFields: '显示字段',
    showColumn: (name: string) => `显示 ${name}`,
    filter: '筛选',
    sql: 'SQL',
    filterQuery: '筛选条件',
    activeFilters: '已应用筛选',
    filterColumn: '筛选列',
    filterOperator: '筛选条件',
    filterValue: '筛选值',
    filterBuilder: '添加筛选条件',
    filterConditions: '已添加条件',
    filterEmptyState: '暂未添加条件，请在上方添加。',
    filterActions: '筛选操作',
    addCondition: '添加条件',
    removeFilterCondition: (name: string) => `移除 ${name} 条件`,
    clearFilters: '清除筛选',
    runFilters: '应用筛选',
    previewRows: '预览行数',
    choose: '请选择…',
    filterOperators: filterOperators({
      eq: '等于', notEq: '不等于', lt: '小于', lte: '小于或等于',
      gt: '大于', gte: '大于或等于', contains: '包含',
      startsWith: '开头为', endsWith: '结尾为', isNull: '为空', isNotNull: '不为空',
    }),
    sqlExamples: 'SQL 示例',
    sqlExamplePreview: '预览前 100 行',
    sqlExampleCount: '统计全部行数',
    sqlExampleNonNull: '查找首列非空记录',
    readOnlySqlTitle: '只读 SQL',
    readOnlySqlMessage: '此查看器为只读模式，不支持 UPDATE、DELETE、INSERT 或其他修改数据的操作。',
    closeReadOnlySql: '关闭只读提示',
    sqlPreviewRows: 'SQL 预览行数',
    formatSql: '格式化 SQL',
    runSql: '运行 SQL',
    sqlEditor: 'SQL 编辑器',
    resizeSqlEditor: '调整 SQL 编辑器高度',
    table: '数据表',
    errorDetails: '错误详情',
    sqlErrorDetails: 'SQL 错误详情',
    copyDetails: '复制详情',
    copiedDetails: '已复制详情',
    couldNotCopyDetails: '无法复制详情',
  },
} as const

export type AppLabels = (typeof labels)[AppLanguage]

export const labelsFor = (language: AppLanguage): AppLabels => labels[language]
